import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  /*
   * `next dev` serves `/_next/*` only to `localhost`, and answers 403 to any
   * other host — so a page opened on `http://127.0.0.1:3000` loads its HTML but
   * none of its scripts, and renders blank.
   *
   * The admin panel cannot avoid that host. `@keystatic/next`'s route handler
   * rewrites `localhost` to `127.0.0.1` internally, and the GitHub App the setup
   * wizard creates registers `http://127.0.0.1/api/keystatic/github/oauth/callback`
   * as a sign-in callback, so the OAuth round trip lands there.
   *
   * This is a development-only allowance: the block exists to stop a random
   * website from reading dev assets, and 127.0.0.1 is the same machine either
   * way. It has no effect on a production build.
   */
  allowedDevOrigins: ["127.0.0.1"],
  images: {
    // All project artwork is first-party SVG generated by scripts/generate-project-art.mjs.
    // The optimizer refuses SVG unless explicitly allowed; the CSP below neutralises
    // scripting inside any served SVG, which is the documented-safe pairing.
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    formats: ["image/avif", "image/webp"],
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-DNS-Prefetch-Control", value: "on" },
        ],
      },
    ];
  },
};

export default nextConfig;
