import type { NextConfig } from "next";

const isDev = process.env.NODE_ENV === "development";

/*
 * Static-site CSP, the documented approach for sites that are not dynamically
 * rendered (nonces would force every page through the server). It blocks
 * off-origin scripts, objects and framing, and pins forms/frames to self.
 * `'unsafe-inline'` is required by Next's own inline bootstrapping; the
 * neutralised JSON-LD sink in JsonLd.tsx is what makes that safe in practice.
 * `frame-src https:` covers the env-configured booking scheduler iframe.
 */
const cspHeader = [
  "default-src 'self'",
  // static.cloudflareinsights.com: Cloudflare Web Analytics beacon (injected on
  // proxied zones); cloudflareinsights.com: where the beacon reports to.
  `script-src 'self' 'unsafe-inline' https://clone-bussiness-help.vercel.app https://vercel.live https://static.cloudflareinsights.com${isDev ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https://avatars.githubusercontent.com",
  "media-src 'self' https:",
  "font-src 'self' https://vercel.live",
  /*
   * The Keystatic panel (GitHub mode) talks to GitHub straight from the
   * browser: GraphQL + contents API on api.github.com and raw files on
   * raw.githubusercontent.com. Without these, the panel renders
   * "Failed to load shell". The public site never fetches them.
   */
  "connect-src 'self' https://api.github.com https://raw.githubusercontent.com https://clone-bussiness-help.vercel.app https://vercel.live https://cloudflareinsights.com wss://ws-us3.pusher.com",
  "frame-src https:",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "upgrade-insecure-requests",
].join("; ");

/*
 * SVG files served straight from /public (the generated project artwork).
 * A direct navigation to such a file renders it as a *document*, where the
 * site-wide policy above — which needs 'unsafe-inline' for Next's own
 * bootstrapping — would allow inline scripts. This rule overrides the CSP for
 * every `.svg` path (later rules win for the same key, per the headers docs):
 * `default-src 'none'` forbids all resource loads including scripts, and
 * `sandbox` puts the document in a restricted origin. Inline styles stay
 * allowed because generated SVGs carry their own `<style>` blocks. `<img>`
 * tags are unaffected — they never execute SVG scripts anyway.
 */
const svgCspHeader =
  "default-src 'none'; style-src 'unsafe-inline'; sandbox";

/*
 * Long-lived image caching. After a first load the browser serves artwork from
 * its own cache and hits the server only in the background (stale-while-
 * revalidate), not on every navigation.
 *
 * Not `immutable`: Keystatic editors can replace an image at the same path, so
 * a replaced file propagates within 7 days instead of being pinned forever.
 * `minimumCacheTTL` gives the /_next/image optimizer output the same lifetime.
 */
const IMAGE_CACHE =
  "public, max-age=604800, stale-while-revalidate=2592000";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  /*
   * `next dev` serves `/_next/*` only to `localhost`, and answers 403 to any
   * other host — so a page opened on `http://127.0.0.1:3000` loads its HTML but
   * none of its scripts, and renders blank.
   *
   * The admin panel cannot avoid that host. `@keystatic/next`'s route handler
   * rewrites `localhost` to `127.0.0.1` internally, and the GitHub App the setup
   * wizard creates registers `http://127.0.0.1/api/keystatic/github/oauth/callback`
   * as a sign-in callback, so the OAuth round trip lands there.
   *
   * This is a development-only allowance: the block exists to stop a random
   * website from reading dev assets, and 127.0.0.1 is the same machine either
   * way. It has no effect on a production build.
   */
  allowedDevOrigins: ["127.0.0.1"],
  images: {
    // All project artwork is first-party SVG generated by scripts/generate-project-art.mjs.
    // The optimizer refuses SVG unless explicitly allowed; the CSP below neutralises
    // scripting inside any served SVG, which is the documented-safe pairing.
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    formats: ["image/avif", "image/webp"],
    /* 7 days: matches the Cache-Control set on the source files below, so a
       cached optimized variant is not discarded after the default short TTL. */
    minimumCacheTTL: 604_800,
    /*
     * Only first-party artwork and brand marks may be optimized. Omitting
     * `search` deliberately: asset-version appends ?v=<hash> for cache
     * busting, so any query on these two prefixes must be accepted.
     */
    localPatterns: [
      { pathname: "/images/**" },
      { pathname: "/logos/**" },
    ],
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-DNS-Prefetch-Control", value: "on" },
          {
            key: "Content-Security-Policy",
            value: cspHeader.replace(/\s{2,}/g, " ").trim(),
          },
          /* Belt and braces with frame-ancestors 'none' above: this site and
             the /keystatic panel must never be frameable. */
          { key: "X-Frame-Options", value: "DENY" },
          /* HTTPS-only deployment (Vercel). */
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
          {
            key: "Permissions-Policy",
            value:
              "camera=(), microphone=(), geolocation=(), payment=()",
          },
          /*
           * The agent-discovery Link headers (RFC 8288 + llmstxt.org v2) used
           * to be static here, but per-path rel="alternate" links need the
           * request path — and a middleware-set Link replaces a configured
           * one rather than merging. src/middleware.ts emits the full set.
           */
        ],
      },
      /* Long-lived caching for static artwork, brand logos and videos: the
         browser reuses what it already has instead of revalidating on every
         navigation. Kept before the SVG rule so that rule stays last (it must
         win on the Content-Security-Policy key). */
      {
        source: "/images/:path*",
        headers: [{ key: "Cache-Control", value: IMAGE_CACHE }],
      },
      {
        source: "/logos/:path*",
        headers: [{ key: "Cache-Control", value: IMAGE_CACHE }],
      },
      /* Last, so it wins for the same header key (see headers docs on
         overriding behavior). Neutralises scripting inside any SVG served
         from /public when someone navigates to the file directly. */
      {
        source: "/:path*.svg",
        headers: [
          { key: "Content-Security-Policy", value: svgCspHeader },
        ],
      },
    ];
  },
};

export default nextConfig;
